import { Injectable } from "@angular/core";

export type User = {
  login: string;
  id: number;
  node_id: string;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
  score: number
}

@Injectable({
  providedIn: 'root',
})

export class UserService {
  constructor() { }

  getUser(): Promise<User[]> {
    return Promise.resolve([
      {
        "login": "ismail",
        "id": 4255,
        "node_id": "MDQ6VXNlcjQyNTU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4255?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismail",
        "html_url": "https://github.com/ismail",
        "followers_url": "https://api.github.com/users/ismail/followers",
        "following_url": "https://api.github.com/users/ismail/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismail/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismail/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismail/subscriptions",
        "organizations_url": "https://api.github.com/users/ismail/orgs",
        "repos_url": "https://api.github.com/users/ismail/repos",
        "events_url": "https://api.github.com/users/ismail/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismail/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailbaskin",
        "id": 358830,
        "node_id": "MDQ6VXNlcjM1ODgzMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/358830?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailbaskin",
        "html_url": "https://github.com/ismailbaskin",
        "followers_url": "https://api.github.com/users/ismailbaskin/followers",
        "following_url": "https://api.github.com/users/ismailbaskin/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailbaskin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailbaskin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailbaskin/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailbaskin/orgs",
        "repos_url": "https://api.github.com/users/ismailbaskin/repos",
        "events_url": "https://api.github.com/users/ismailbaskin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailbaskin/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailakbudak",
        "id": 4919272,
        "node_id": "MDQ6VXNlcjQ5MTkyNzI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4919272?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailakbudak",
        "html_url": "https://github.com/ismailakbudak",
        "followers_url": "https://api.github.com/users/ismailakbudak/followers",
        "following_url": "https://api.github.com/users/ismailakbudak/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailakbudak/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailakbudak/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailakbudak/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailakbudak/orgs",
        "repos_url": "https://api.github.com/users/ismailakbudak/repos",
        "events_url": "https://api.github.com/users/ismailakbudak/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailakbudak/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "IsmailM",
        "id": 5578375,
        "node_id": "MDQ6VXNlcjU1NzgzNzU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5578375?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/IsmailM",
        "html_url": "https://github.com/IsmailM",
        "followers_url": "https://api.github.com/users/IsmailM/followers",
        "following_url": "https://api.github.com/users/IsmailM/following{/other_user}",
        "gists_url": "https://api.github.com/users/IsmailM/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/IsmailM/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/IsmailM/subscriptions",
        "organizations_url": "https://api.github.com/users/IsmailM/orgs",
        "repos_url": "https://api.github.com/users/IsmailM/repos",
        "events_url": "https://api.github.com/users/IsmailM/events{/privacy}",
        "received_events_url": "https://api.github.com/users/IsmailM/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "smakosh",
        "id": 20082141,
        "node_id": "MDQ6VXNlcjIwMDgyMTQx",
        "avatar_url": "https://avatars.githubusercontent.com/u/20082141?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/smakosh",
        "html_url": "https://github.com/smakosh",
        "followers_url": "https://api.github.com/users/smakosh/followers",
        "following_url": "https://api.github.com/users/smakosh/following{/other_user}",
        "gists_url": "https://api.github.com/users/smakosh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/smakosh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/smakosh/subscriptions",
        "organizations_url": "https://api.github.com/users/smakosh/orgs",
        "repos_url": "https://api.github.com/users/smakosh/repos",
        "events_url": "https://api.github.com/users/smakosh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/smakosh/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismail1432",
        "id": 13260307,
        "node_id": "MDQ6VXNlcjEzMjYwMzA3",
        "avatar_url": "https://avatars.githubusercontent.com/u/13260307?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismail1432",
        "html_url": "https://github.com/ismail1432",
        "followers_url": "https://api.github.com/users/ismail1432/followers",
        "following_url": "https://api.github.com/users/ismail1432/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismail1432/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismail1432/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismail1432/subscriptions",
        "organizations_url": "https://api.github.com/users/ismail1432/orgs",
        "repos_url": "https://api.github.com/users/ismail1432/repos",
        "events_url": "https://api.github.com/users/ismail1432/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismail1432/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailsunni",
        "id": 1421861,
        "node_id": "MDQ6VXNlcjE0MjE4NjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1421861?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailsunni",
        "html_url": "https://github.com/ismailsunni",
        "followers_url": "https://api.github.com/users/ismailsunni/followers",
        "following_url": "https://api.github.com/users/ismailsunni/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailsunni/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailsunni/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailsunni/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailsunni/orgs",
        "repos_url": "https://api.github.com/users/ismailsunni/repos",
        "events_url": "https://api.github.com/users/ismailsunni/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailsunni/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismail0234",
        "id": 20711301,
        "node_id": "MDQ6VXNlcjIwNzExMzAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/20711301?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismail0234",
        "html_url": "https://github.com/ismail0234",
        "followers_url": "https://api.github.com/users/ismail0234/followers",
        "following_url": "https://api.github.com/users/ismail0234/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismail0234/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismail0234/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismail0234/subscriptions",
        "organizations_url": "https://api.github.com/users/ismail0234/orgs",
        "repos_url": "https://api.github.com/users/ismail0234/repos",
        "events_url": "https://api.github.com/users/ismail0234/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismail0234/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailmechbal",
        "id": 1128114,
        "node_id": "MDQ6VXNlcjExMjgxMTQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1128114?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailmechbal",
        "html_url": "https://github.com/ismailmechbal",
        "followers_url": "https://api.github.com/users/ismailmechbal/followers",
        "following_url": "https://api.github.com/users/ismailmechbal/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailmechbal/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailmechbal/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailmechbal/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailmechbal/orgs",
        "repos_url": "https://api.github.com/users/ismailmechbal/repos",
        "events_url": "https://api.github.com/users/ismailmechbal/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailmechbal/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismail-syed",
        "id": 6130700,
        "node_id": "MDQ6VXNlcjYxMzA3MDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6130700?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismail-syed",
        "html_url": "https://github.com/ismail-syed",
        "followers_url": "https://api.github.com/users/ismail-syed/followers",
        "following_url": "https://api.github.com/users/ismail-syed/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismail-syed/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismail-syed/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismail-syed/subscriptions",
        "organizations_url": "https://api.github.com/users/ismail-syed/orgs",
        "repos_url": "https://api.github.com/users/ismail-syed/repos",
        "events_url": "https://api.github.com/users/ismail-syed/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismail-syed/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismail9k",
        "id": 11035467,
        "node_id": "MDQ6VXNlcjExMDM1NDY3",
        "avatar_url": "https://avatars.githubusercontent.com/u/11035467?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismail9k",
        "html_url": "https://github.com/ismail9k",
        "followers_url": "https://api.github.com/users/ismail9k/followers",
        "following_url": "https://api.github.com/users/ismail9k/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismail9k/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismail9k/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismail9k/subscriptions",
        "organizations_url": "https://api.github.com/users/ismail9k/orgs",
        "repos_url": "https://api.github.com/users/ismail9k/repos",
        "events_url": "https://api.github.com/users/ismail9k/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismail9k/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "elhardoum",
        "id": 7893147,
        "node_id": "MDQ6VXNlcjc4OTMxNDc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7893147?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/elhardoum",
        "html_url": "https://github.com/elhardoum",
        "followers_url": "https://api.github.com/users/elhardoum/followers",
        "following_url": "https://api.github.com/users/elhardoum/following{/other_user}",
        "gists_url": "https://api.github.com/users/elhardoum/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/elhardoum/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/elhardoum/subscriptions",
        "organizations_url": "https://api.github.com/users/elhardoum/orgs",
        "repos_url": "https://api.github.com/users/elhardoum/repos",
        "events_url": "https://api.github.com/users/elhardoum/events{/privacy}",
        "received_events_url": "https://api.github.com/users/elhardoum/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailbozkurt",
        "id": 7279627,
        "node_id": "MDQ6VXNlcjcyNzk2Mjc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7279627?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailbozkurt",
        "html_url": "https://github.com/ismailbozkurt",
        "followers_url": "https://api.github.com/users/ismailbozkurt/followers",
        "following_url": "https://api.github.com/users/ismailbozkurt/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailbozkurt/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailbozkurt/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailbozkurt/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailbozkurt/orgs",
        "repos_url": "https://api.github.com/users/ismailbozkurt/repos",
        "events_url": "https://api.github.com/users/ismailbozkurt/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailbozkurt/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailnguyen",
        "id": 11783843,
        "node_id": "MDQ6VXNlcjExNzgzODQz",
        "avatar_url": "https://avatars.githubusercontent.com/u/11783843?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailnguyen",
        "html_url": "https://github.com/ismailnguyen",
        "followers_url": "https://api.github.com/users/ismailnguyen/followers",
        "following_url": "https://api.github.com/users/ismailnguyen/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailnguyen/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailnguyen/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailnguyen/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailnguyen/orgs",
        "repos_url": "https://api.github.com/users/ismailnguyen/repos",
        "events_url": "https://api.github.com/users/ismailnguyen/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailnguyen/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "sogko",
        "id": 78585,
        "node_id": "MDQ6VXNlcjc4NTg1",
        "avatar_url": "https://avatars.githubusercontent.com/u/78585?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sogko",
        "html_url": "https://github.com/sogko",
        "followers_url": "https://api.github.com/users/sogko/followers",
        "following_url": "https://api.github.com/users/sogko/following{/other_user}",
        "gists_url": "https://api.github.com/users/sogko/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sogko/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sogko/subscriptions",
        "organizations_url": "https://api.github.com/users/sogko/orgs",
        "repos_url": "https://api.github.com/users/sogko/repos",
        "events_url": "https://api.github.com/users/sogko/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sogko/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismaild",
        "id": 429985,
        "node_id": "MDQ6VXNlcjQyOTk4NQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/429985?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismaild",
        "html_url": "https://github.com/ismaild",
        "followers_url": "https://api.github.com/users/ismaild/followers",
        "following_url": "https://api.github.com/users/ismaild/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismaild/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismaild/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismaild/subscriptions",
        "organizations_url": "https://api.github.com/users/ismaild/orgs",
        "repos_url": "https://api.github.com/users/ismaild/repos",
        "events_url": "https://api.github.com/users/ismaild/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismaild/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "CodeIsmail",
        "id": 8437935,
        "node_id": "MDQ6VXNlcjg0Mzc5MzU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8437935?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CodeIsmail",
        "html_url": "https://github.com/CodeIsmail",
        "followers_url": "https://api.github.com/users/CodeIsmail/followers",
        "following_url": "https://api.github.com/users/CodeIsmail/following{/other_user}",
        "gists_url": "https://api.github.com/users/CodeIsmail/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CodeIsmail/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CodeIsmail/subscriptions",
        "organizations_url": "https://api.github.com/users/CodeIsmail/orgs",
        "repos_url": "https://api.github.com/users/CodeIsmail/repos",
        "events_url": "https://api.github.com/users/CodeIsmail/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CodeIsmail/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailkocacan",
        "id": 3339197,
        "node_id": "MDQ6VXNlcjMzMzkxOTc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3339197?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailkocacan",
        "html_url": "https://github.com/ismailkocacan",
        "followers_url": "https://api.github.com/users/ismailkocacan/followers",
        "following_url": "https://api.github.com/users/ismailkocacan/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailkocacan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailkocacan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailkocacan/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailkocacan/orgs",
        "repos_url": "https://api.github.com/users/ismailkocacan/repos",
        "events_url": "https://api.github.com/users/ismailkocacan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailkocacan/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismail-codar",
        "id": 282104,
        "node_id": "MDQ6VXNlcjI4MjEwNA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/282104?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismail-codar",
        "html_url": "https://github.com/ismail-codar",
        "followers_url": "https://api.github.com/users/ismail-codar/followers",
        "following_url": "https://api.github.com/users/ismail-codar/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismail-codar/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismail-codar/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismail-codar/subscriptions",
        "organizations_url": "https://api.github.com/users/ismail-codar/orgs",
        "repos_url": "https://api.github.com/users/ismail-codar/repos",
        "events_url": "https://api.github.com/users/ismail-codar/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismail-codar/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ikismail",
        "id": 17190913,
        "node_id": "MDQ6VXNlcjE3MTkwOTEz",
        "avatar_url": "https://avatars.githubusercontent.com/u/17190913?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ikismail",
        "html_url": "https://github.com/ikismail",
        "followers_url": "https://api.github.com/users/ikismail/followers",
        "following_url": "https://api.github.com/users/ikismail/following{/other_user}",
        "gists_url": "https://api.github.com/users/ikismail/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ikismail/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ikismail/subscriptions",
        "organizations_url": "https://api.github.com/users/ikismail/orgs",
        "repos_url": "https://api.github.com/users/ikismail/repos",
        "events_url": "https://api.github.com/users/ikismail/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ikismail/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "xd4rker",
        "id": 7257362,
        "node_id": "MDQ6VXNlcjcyNTczNjI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7257362?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xd4rker",
        "html_url": "https://github.com/xd4rker",
        "followers_url": "https://api.github.com/users/xd4rker/followers",
        "following_url": "https://api.github.com/users/xd4rker/following{/other_user}",
        "gists_url": "https://api.github.com/users/xd4rker/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xd4rker/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xd4rker/subscriptions",
        "organizations_url": "https://api.github.com/users/xd4rker/orgs",
        "repos_url": "https://api.github.com/users/xd4rker/repos",
        "events_url": "https://api.github.com/users/xd4rker/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xd4rker/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "liamsi",
        "id": 7441766,
        "node_id": "MDQ6VXNlcjc0NDE3NjY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7441766?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/liamsi",
        "html_url": "https://github.com/liamsi",
        "followers_url": "https://api.github.com/users/liamsi/followers",
        "following_url": "https://api.github.com/users/liamsi/following{/other_user}",
        "gists_url": "https://api.github.com/users/liamsi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/liamsi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/liamsi/subscriptions",
        "organizations_url": "https://api.github.com/users/liamsi/orgs",
        "repos_url": "https://api.github.com/users/liamsi/repos",
        "events_url": "https://api.github.com/users/liamsi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/liamsi/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailismail",
        "id": 451978,
        "node_id": "MDQ6VXNlcjQ1MTk3OA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/451978?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailismail",
        "html_url": "https://github.com/ismailismail",
        "followers_url": "https://api.github.com/users/ismailismail/followers",
        "following_url": "https://api.github.com/users/ismailismail/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailismail/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailismail/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailismail/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailismail/orgs",
        "repos_url": "https://api.github.com/users/ismailismail/repos",
        "events_url": "https://api.github.com/users/ismailismail/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailismail/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismcagdas",
        "id": 4133525,
        "node_id": "MDQ6VXNlcjQxMzM1MjU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4133525?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismcagdas",
        "html_url": "https://github.com/ismcagdas",
        "followers_url": "https://api.github.com/users/ismcagdas/followers",
        "following_url": "https://api.github.com/users/ismcagdas/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismcagdas/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismcagdas/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismcagdas/subscriptions",
        "organizations_url": "https://api.github.com/users/ismcagdas/orgs",
        "repos_url": "https://api.github.com/users/ismcagdas/repos",
        "events_url": "https://api.github.com/users/ismcagdas/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismcagdas/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "dbtek",
        "id": 310612,
        "node_id": "MDQ6VXNlcjMxMDYxMg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/310612?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dbtek",
        "html_url": "https://github.com/dbtek",
        "followers_url": "https://api.github.com/users/dbtek/followers",
        "following_url": "https://api.github.com/users/dbtek/following{/other_user}",
        "gists_url": "https://api.github.com/users/dbtek/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dbtek/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dbtek/subscriptions",
        "organizations_url": "https://api.github.com/users/dbtek/orgs",
        "repos_url": "https://api.github.com/users/dbtek/repos",
        "events_url": "https://api.github.com/users/dbtek/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dbtek/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "IsmailBarkani",
        "id": 51321011,
        "node_id": "MDQ6VXNlcjUxMzIxMDEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/51321011?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/IsmailBarkani",
        "html_url": "https://github.com/IsmailBarkani",
        "followers_url": "https://api.github.com/users/IsmailBarkani/followers",
        "following_url": "https://api.github.com/users/IsmailBarkani/following{/other_user}",
        "gists_url": "https://api.github.com/users/IsmailBarkani/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/IsmailBarkani/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/IsmailBarkani/subscriptions",
        "organizations_url": "https://api.github.com/users/IsmailBarkani/orgs",
        "repos_url": "https://api.github.com/users/IsmailBarkani/repos",
        "events_url": "https://api.github.com/users/IsmailBarkani/events{/privacy}",
        "received_events_url": "https://api.github.com/users/IsmailBarkani/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailxebia",
        "id": 18502861,
        "node_id": "MDQ6VXNlcjE4NTAyODYx",
        "avatar_url": "https://avatars.githubusercontent.com/u/18502861?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailxebia",
        "html_url": "https://github.com/ismailxebia",
        "followers_url": "https://api.github.com/users/ismailxebia/followers",
        "following_url": "https://api.github.com/users/ismailxebia/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailxebia/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailxebia/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailxebia/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailxebia/orgs",
        "repos_url": "https://api.github.com/users/ismailxebia/repos",
        "events_url": "https://api.github.com/users/ismailxebia/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailxebia/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "ismailarilik",
        "id": 17585121,
        "node_id": "MDQ6VXNlcjE3NTg1MTIx",
        "avatar_url": "https://avatars.githubusercontent.com/u/17585121?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ismailarilik",
        "html_url": "https://github.com/ismailarilik",
        "followers_url": "https://api.github.com/users/ismailarilik/followers",
        "following_url": "https://api.github.com/users/ismailarilik/following{/other_user}",
        "gists_url": "https://api.github.com/users/ismailarilik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ismailarilik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ismailarilik/subscriptions",
        "organizations_url": "https://api.github.com/users/ismailarilik/orgs",
        "repos_url": "https://api.github.com/users/ismailarilik/repos",
        "events_url": "https://api.github.com/users/ismailarilik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ismailarilik/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "IsmailAbdirahman",
        "id": 56909567,
        "node_id": "MDQ6VXNlcjU2OTA5NTY3",
        "avatar_url": "https://avatars.githubusercontent.com/u/56909567?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/IsmailAbdirahman",
        "html_url": "https://github.com/IsmailAbdirahman",
        "followers_url": "https://api.github.com/users/IsmailAbdirahman/followers",
        "following_url": "https://api.github.com/users/IsmailAbdirahman/following{/other_user}",
        "gists_url": "https://api.github.com/users/IsmailAbdirahman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/IsmailAbdirahman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/IsmailAbdirahman/subscriptions",
        "organizations_url": "https://api.github.com/users/IsmailAbdirahman/orgs",
        "repos_url": "https://api.github.com/users/IsmailAbdirahman/repos",
        "events_url": "https://api.github.com/users/IsmailAbdirahman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/IsmailAbdirahman/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      },
      {
        "login": "Ismail-ElAyadi",
        "id": 54063023,
        "node_id": "MDQ6VXNlcjU0MDYzMDIz",
        "avatar_url": "https://avatars.githubusercontent.com/u/54063023?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Ismail-ElAyadi",
        "html_url": "https://github.com/Ismail-ElAyadi",
        "followers_url": "https://api.github.com/users/Ismail-ElAyadi/followers",
        "following_url": "https://api.github.com/users/Ismail-ElAyadi/following{/other_user}",
        "gists_url": "https://api.github.com/users/Ismail-ElAyadi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Ismail-ElAyadi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Ismail-ElAyadi/subscriptions",
        "organizations_url": "https://api.github.com/users/Ismail-ElAyadi/orgs",
        "repos_url": "https://api.github.com/users/Ismail-ElAyadi/repos",
        "events_url": "https://api.github.com/users/Ismail-ElAyadi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Ismail-ElAyadi/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1
      }
    ]
    )
  }
}